services:
  local-network-monitor:
    image: network-monitor:latest
    build: .
    container_name: local-network-monitor
    restart: unless-stopped
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
